### ISSUE TITLE
Stuck on grant access screen. kernel 6.3.8-200

### ISSUE THREAD

**Issue by Xeo23** [legacyO7/Aurora#11]
I have installed it using copr on f38 it stucked on the grant access page and nothing happens when i click the button (grant access).

**Comment by legacyO7** [comment]
Pls provide the log located in /tmp/ar.log

**Comment by pragit-raj-sharma** [comment]
[ar.log](https://github.com/legacyO7/Aurora/files/11839995/ar.log)

**Comment by Xeo23** [comment]
> $ mokutil --sb-state
> SecureBoot disabled
> $ chmod +x /tmp/legacy07.aurora/permission_checker.sh
> $ type pkexec
> pkexec is /bin/pkexec
> $ chmod +x /tmp/legacy07.aurora/battery_manager.sh
> $ chmod +x /tmp/legacy07.aurora/mainline_controller.sh
> $ /tmp/legacy07.aurora/permission_checker.sh /sys/class/leds/asus::kbd_backlight/kbd_rgb_state
> true
> $ /tmp/legacy07.aurora/permission_checker.sh /sys/class/leds/asus::kbd_backlight/kbd_rgb_mode
> $ /tmp/legacy07.aurora/permission_checker.sh /sys/class/leds/asus::kbd_backlight/brightness
> true
> $ /tmp/legacy07.aurora/mainline_controller.sh brightness 1
> $ /tmp/legacy07.aurora/mainline_controller.sh mode 1 0 104 15 226 0
> $ /tmp/legacy07.aurora/mainline_controller.sh state 1 1 1 0 0
> saved
0 0
> $ /tmp/legacy07.aurora/mainline_controller.sh mode 1 0 223 205 249 0
> 1 0 223 205 249 0
> saved
> $ /tmp/legacy07.aurora/mainline_controller.sh mode 1 0 104 15 226 0
> 1 0 104 15 226 0
> saved
> $ /tmp/legacy07.aurora/mainline_controller.sh state 1 1 1 1 0
> 1 1 1 1 0
> saved
> $ /tmp/legacy07.aurora/mainline_controller.sh state 1 1 1 0 0
> 1 1 1 0 0
> saved
> $ /tmp/legacy07.aurora/mainline_controller.sh mode 1 9 104 15 226 0
> 1 9 104 15 226 0
> saved
> $ /tmp/legacy07.aurora/mainline_controller.sh mode 1 0 104 15 226 0
> 1 0 104 15 226 0
> saved
> $ /tmp/legacy07.aurora/mainline_controller.sh brightness 3
> $ /tmp/legacy07.aurora/mainline_controller.sh brightness 0
> $ /tmp/legacy07.aurora/mainline_controller.sh brightness 1
> $ /tmp/legacy07.aurora/mainline_controller.sh mode 1 1 104 15 226 0
> 1 1 104 15 226 0
> saved
> $ /tmp/legacy07.aurora/mainline_controller.sh mode 1 2 104 15 226 0
> 1 2 104 15 226 0
> saved
> $ /tmp/legacy07.aurora/mainline_controller.sh mode 1 2 104 15 226 2
> 1 2 104 15 226 2
> saved
> $ /tmp/legacy07.aurora/mainline_controller.sh mode 1 2 104 15 226 0
> 1 2 104 15 226 0
> saved
> $ /tmp/legacy07.aurora/mainline_controller.sh mode 1 0 104 15 226 0
> 1 0 104 15 226 0
> saved

**Comment by legacyO7** [comment]
the log seems fine. You had passed the Authorization screen with proper permissions and had reached the control screen, according to the log you provided

**Comment by Xeo23** [comment]
Su permissions required to run it ?
When I normally opened it from menu, it stucked on the grant access screen but then i tried to run it from terminal with sudo and it worked

**Comment by legacyO7** [comment]
Yes. Sudo permissions are required but it doesn't need to be run from terminal with sudo. It can be normally opened like any other app and it uses pkexec to get the sudo permission if required. 
Provide the log while running the app without sudo permissions.

**Comment by Xeo23** [comment]
> $ mokutil --sb-state
> SecureBoot disabled
> $ chmod +x /tmp/legacy07.aurora/permission_checker.sh
> $ type pkexec
> pkexec is /usr/bin/pkexec
> $ chmod +x /tmp/legacy07.aurora/battery_manager.sh
> $ chmod +x /tmp/legacy07.aurora/mainline_controller.sh
> $ /tmp/legacy07.aurora/permission_checker.sh /sys/class/leds/asus::kbd_backlight/kbd_rgb_state
> $ pkexec --disable-internal-agent /tmp/legacy07.aurora/mainline_controller.sh init /tmp/legacy07.aurora 50
> Refusing to render service to dead parents.
> $ /tmp/legacy07.aurora/permission_checker.sh /sys/class/leds/asus::kbd_backlight/kbd_rgb_state
> false
> $ /tmp/legacy07.aurora/permission_checker.sh /sys/class/leds/asus::kbd_backlight/kbd_rgb_state
> $ pkexec --disable-internal-agent /tmp/legacy07.aurora/mainline_controller.sh init /tmp/legacy07.aurora 50
> Refusing to render service to dead parents.
> $ /tmp/legacy07.aurora/permission_checker.sh /sys/class/leds/asus::kbd_backlight/kbd_rgb_state
> false

**Comment by legacyO7** [comment]
I'm unable to reproduce this issue on my f38-kernel 6.3.8-200.

Are you getting the same error when running the command
`pkexec --disable-internal-agent /tmp/legacy07.aurora/mainline_controller.sh init /tmp/legacy07.aurora 50` 
 by manually in the terminal?

**Comment by Xeo23** [comment]
I got the password prompt and this is the terminal output.

![image](https://github.com/legacyO7/Aurora/assets/65211497/73a97b8c-c845-4a1e-bf5b-b6813414a7d3)


❯ pkexec --disable-internal-agent /tmp/legacy07.aurora/mainline_controller.sh init /tmp/legacy07.aurora 50
modprobe: FATAL: Module faustus not found.
50
Setting charging threshold to 50 %...
Created symlink /etc/systemd/system/multi-user.target.wants/aurora-controller.service → /usr/lib/systemd/system/aurora-controller.service.
Created symlink /etc/systemd/system/suspend.target.wants/aurora-controller.service → /usr/lib/systemd/system/aurora-controller.service.
Created symlink /etc/systemd/system/hibernate.target.wants/aurora-controller.service → /usr/lib/systemd/system/aurora-controller.service.
Created symlink /etc/systemd/system/hybrid-sleep.target.wants/aurora-controller.service → /usr/lib/systemd/system/aurora-controller.service.
Created symlink /etc/systemd/system/suspend-then-hibernate.target.wants/aurora-controller.service → /usr/lib/systemd/system/aurora-controller.service.

**Comment by legacyO7** [comment]
does running `/usr/bin/aurora/aurora` by terminal without the root privileges also have the same result?

**Comment by Xeo23** [comment]
Now it is stucked on checking compatibility screen.

![image](https://github.com/legacyO7/Aurora/assets/65211497/117b2de3-1e8e-4eb3-beb6-8e52f818c8bf)

❯ /usr/bin/aurora/aurora
Gtk-Message: 01:06:54.061: Failed to load module "appmenu-gtk-module"
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PathAccessException: Cannot delete file, path = '/tmp/ar.log' (OS Error: Operation not permitted, errno = 1)
#0      _File.throwIfError (dart:io/file_impl.dart:675)
#1      _File._deleteSync (dart:io/file_impl.dart:329)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:424)
#3      TerminalSourceImpl.clearLog (package:aurora/user_interface/terminal/data/source/terminal_source_impl.dart:135)
#4      initDI.<anonymous closure> (package:aurora/data/di/di.dart:62)
#5      _ServiceFactory.getObject (package:get_it/get_it_impl.dart:160)
#6      _GetItImplementation.get (package:get_it/get_it_impl.dart:409)
#7      _GetItImplementation.call (package:get_it/get_it_impl.dart:430)
#8      initDI.<anonymous closure> (package:aurora/data/di/di.dart:59)
#9      _ServiceFactory.getObject (package:get_it/get_it_impl.dart:160)
#10     _GetItImplementation.get (package:get_it/get_it_impl.dart:409)
#11     _GetItImplementation.call (package:get_it/get_it_impl.dart:430)
#12     initDI.<anonymous closure> (package:aurora/data/di/di.dart:52)
#13     _ServiceFactory.getObject (package:get_it/get_it_impl.dart:160)
#14     _GetItImplementation.get (package:get_it/get_it_impl.dart:409)
#15     _GetItImplementation.call (package:get_it/get_it_impl.dart:430)
#16     initDI.<anonymous closure> (package:aurora/data/di/di.dart:47)
#17     _ServiceFactory.getObject (package:get_it/get_it_impl.dart:160)
#18     _GetItImplementation.get (package:get_it/get_it_impl.dart:409)
#19     _GetItImplementation.call (package:get_it/get_it_impl.dart:430)
#20     Aurora.build (package:aurora/main.dart:68)
#21     StatelessElement.build (package:flutter/src/widgets/framework.dart:5156)
#22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5086)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5068)
#25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062)
#26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:3708)
#28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111)
#29     Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5068)
#31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062)
#32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:3708)
#34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111)
#35     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251)
#36     Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5068)
#38     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5242)
#39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062)
#40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:3708)
#42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111)
#43     Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5068)
#45     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062)
#46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:3708)
#48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111)
#49     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251)
#50     Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#51     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5068)
#52     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5242)
#53     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062)
#54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:3708)
#56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111)
#57     Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#58     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5068)
#59     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062)
#60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971)
#61     Element.updateChild (package:flutter/src/widgets/framework.dart:3708)
#62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111)
#63     Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#64     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5068)
#65     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062)
#66     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971)
#67     Element.updateChild (package:flutter/src/widgets/framework.dart:3708)
#68     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1240)
#69     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1209)
#70     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1156)
#71     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2720)
#72     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1155)
#73     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:988)
#74     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:968)
#75     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18)
#76     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398)
#77     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429)
#78     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189)

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PathAccessException: Deletion failed, path = '/tmp/legacy07.aurora' (OS Error: Permission denied, errno = 13)
#0      _Directory._deleteSync (dart:io/directory_impl.dart:193)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:424)
#2      SetupRepoImpl.initSetup (package:aurora/user_interface/setup/domain/repository/setup_repo_impl.dart:44)
#3      SetupBloc._initSetup (package:aurora/user_interface/setup/presentation/state/setup_bloc.dart:37)
<asynchronous suspension>
#4      Bloc.on.<anonymous closure>.handleEvent (package:bloc/src/bloc.dart:226)
<asynchronous suspension>

**Comment by legacyO7** [comment]
You must have run aurora with root privileges at some point which made the ar.log created by root, which cannot be deleted without root privileges

**Comment by Xeo23** [comment]
Ok I got it working fine without root privileges. Thanks
