### ISSUE TITLE
Aurora says I don't have ASUS laptop...

### ISSUE THREAD

**Issue by senjabl** [legacyO7/Aurora#12]
Hello,

I have ASUS XF505DT Laptop with Manjaro linux and Plasma desktop. When I start Aurora, it says "this ain't ASUS. I have no business there".  :-)

**To Reproduce**
-Start Aurora, 
-It says "this ain't ASUS. I have no business there".  :-)

**Expected behavior**
Application is suppose to start application.

**Screenshots**
![Screenshot_20230705_141507-1](https://github.com/legacyO7/Aurora/assets/9935967/0a593ed4-3b7e-4b51-9265-ed0aa027544a)

**Desktop (please complete the following information):**
Operating System: Manjaro Linux 

**Additional context**
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.106.0
Qt Version: 5.15.9
Kernel Version: 6.3.5-2-MANJARO (64-bit)
Graphics Platform: X11
Processors: 8 × AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx
Memory: 13,6 GiB of RAM
Graphics Processor: AMD Radeon Vega 8 Graphics
Manufacturer: ASUSTeK COMPUTER INC.
Product Name: TUF Gaming FX505DT_FX505DT
System Version: 1.0

Tried with kernels 6.1.31 , 6.2.16 and 6.3.5
Also I tried with appimages aurora-linux-3.1.2-beta and aurora-linux-3.0.0
Also tried with source from github.

**Aurora logfile**
No logs were generated in /tmp/, /var/, /var/log/ ...

**Comment by legacyO7** [comment]
please provide the output of `` cat /sys/devices/virtual/dmi/id/product_name`` and `` cat /sys/devices/virtual/dmi/id/sys_vendor ``

**Comment by senjabl** [comment]
OK,
`cat /sys/devices/virtual/dmi/id/product_name`
`TUF Gaming FX505DT_FX505DT`

`cat /sys/devices/virtual/dmi/id/sys_vendor`
`ASUSTeK COMPUTER INC.`

**Comment by legacyO7** [comment]
Please run the app from the updated source `canary` branch and see if it's fixed

**Comment by senjabl** [comment]
It recognized Laptop beut got stuck on screen with "Grant access"

**Comment by legacyO7** [comment]
please provide the terminal log

**Comment by senjabl** [comment]
[ar.log](https://github.com/legacyO7/Aurora/files/11958473/ar.log)

**Comment by legacyO7** [comment]
this happens when the working directory doesn't exist (often happens in debug mode). a fallback directory is added now if the current working directory is invalid

**Comment by senjabl** [comment]
Hello, sorry for delay.
After your latest fixes, application starts. 
However, it does not change color of RGB keyboard leds. Intensity changing works and battery treshold works.
ROG Aura control from Asusd project also do not work.

When I install your fork of Faustus drivers, it works.

**Comment by legacyO7** [comment]
Backlight control in distros with kernel 6.1 and above should work without Faustus module. Please provide the log in mainline mode if possible.

**Comment by senjabl** [comment]
Strange, ar.log is created only if I build application and run it from release/bundle folder. If I run app with `flutter run` or from debug/bundle folder, it does not create logfile.

[ar.log](https://github.com/legacyO7/Aurora/files/11975371/ar.log)

**Comment by legacyO7** [comment]
logfile wont be created if you are running the app from source, instead it just prints the log in terminal. If you wanna change this behaviour, just negate this condition
https://github.com/legacyO7/Aurora/blob/ddc56d6714a3570d4bfb1431f5e2fb219c900282/lib/utility/ar_widgets/ar_logger.dart#L47

Seems like it didnt logged any errors in mainline mode. Is aurora stable v2 working in mainline mode?
https://github.com/legacyO7/Aurora/blob/5d6266c01fc36fe3c195e3c030e36d0bdce14064/lib/user_interface/home/domain/home_repo_impl.dart#L86C3-L86C3
You can remove this condition to bypass the device compatibility check in the `stable` branch.
Please privide the log of v2 if ibacklight cotrol isn't working in mainline mode. Since it rely on script based control, it might can give more insight

**Comment by senjabl** [comment]
Hello, I am traveling. Will try when I get back. 
According to 

[https://gitlab.com/asus-linux/asusctl/-/issues/349](url)

for certain TUF laptops asus-wmi kernel module need patching to work.

**Comment by legacyO7** [comment]
Added option to enforce faustus mode, which will force aurora to run in faustus mode in cases like this. ( Settings > Enforce Faustus )
