### ISSUE TITLE
/lib/systemd/system bad permissions

### ISSUE THREAD

**Issue by NativoDigital** [legacyO7/Aurora#13]
Hi,

It works pretty well. I have installed aurora_3.5.7-stable+1_amd64.deb on Debian 12.2. The laptop is a F15 FX506HC

Every time it starts, just after asking for root credentials, it changes all the file permissions under /lib/systemd/system/ to chmod 647 and folders to chmod 757.

Even while the app is opened I can patch the problem with something as `find . -type f -exec chmod 644 {} \; && find . -type d -exec chmod 755 {} \;` and it still works, so I don't understand why it need to change ALL those system services permissions. After all it is working as root.

Thank you for your good work!
Best regards

**Comment by legacyO7** [comment]
It was necessary during the early stages of Aurora, but it is no longer required.
