### ISSUE TITLE
Backlit is not working on kernels starting from version 6.1 and above.

### ISSUE THREAD

**Issue by Xeo23** [legacyO7/Aurora#8]
I have two kernels installed in my fedora system. One is 6.0.18, 6.1.8 and 6.1.9. Backlit works on the 6.0.18 version but not on any other versions above it.

**Comment by legacyO7** [comment]
Faustus module has issues with kernel 6.1 and above.  A [workaround](https://github.com/legacyO7/faustus/commit/1af9389c8ec907f810920dc876b68bf0c7607193) is provided in [this fork](https://github.com/legacyO7/faustus) which might fix the issue. If this doesn't, please report back with a proper error log

**Comment by Xeo23** [comment]
Thanks it worked.
But now there is another problem. The aurora version 1.3.2 stable works fine but other latest versions are stucked at (install packages) page showing (nothing to install).

![2023-02-04_20-50](https://user-images.githubusercontent.com/65211497/216775267-fbbab3ae-be44-43d2-88a3-f5918b649a7a.png)

 It works when i run them with root permissions from terminal but doesn't show the led modes (static, strobing, colour cycle, breathing) .

![2023-02-04_20-49](https://user-images.githubusercontent.com/65211497/216775235-f366453d-5746-44bb-b7b6-f704e8a76e7b.png)

**Comment by legacyO7** [comment]
The reason for aurora to enter setup mode is that Faustus module isn't installed properly.

Anyhow kernel 6.1 or above doesn't need faustus module to control keyboard backlit. This change is being implemented in aurora, starting from 1.7.5-beta+1

**Comment by Xeo23** [comment]
I have installed it properly.
